"""HTML ID constants for Phase 3: Review & Commit"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/html_ids.ipynb.

# %% auto #0
__all__ = ['ReviewHtmlIds']

# %% ../nbs/html_ids.ipynb #c3d4e5f6
# Framework-agnostic — no external imports needed

class ReviewHtmlIds:
    """HTML ID constants for Phase 3: Review & Commit."""

    @staticmethod
    def as_selector(
        id_str:str  # The HTML ID to convert
    ) -> str:  # CSS selector with # prefix
        """Convert an ID to a CSS selector format."""
        return f"#{id_str}"

    # Main Layout
    REVIEW_CONTAINER = "sd-review-container"
    READER_VIEW = "sd-reader-view"
    COMMIT_SUMMARY = "sd-commit-summary"
