"""Time formatting and source info display utilities for review cards"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto #0
__all__ = ['format_time', 'format_duration', 'truncate_id', 'format_char_range', 'format_source_info']

# %% ../nbs/utils.ipynb #review-utils-imports
from typing import Optional

# %% ../nbs/utils.ipynb #review-utils-format-time
def format_time(
    seconds:Optional[float]  # Time in seconds
) -> str:  # Formatted time string (m:ss.s)
    """Format seconds as m:ss.s for sub-second display."""
    if seconds is None:
        return "-:--.-"
    minutes = int(seconds // 60)
    secs = seconds % 60
    return f"{minutes}:{secs:04.1f}"

# %% ../nbs/utils.ipynb #review-utils-format-duration
def format_duration(
    start:Optional[float],  # Start time in seconds
    end:Optional[float],  # End time in seconds
) -> str:  # Formatted duration string (e.g., "3.2s")
    """Format duration from start/end times."""
    if start is None or end is None:
        return "-.-s"
    duration = end - start
    return f"{duration:.1f}s"

# %% ../nbs/utils.ipynb #review-utils-truncate-id
def truncate_id(
    id_str:Optional[str],  # Full ID string
    length:int=8,  # Number of characters to keep
) -> str:  # Truncated ID with ellipsis if needed
    """Truncate an ID string for display, adding ellipsis if truncated."""
    if id_str is None:
        return "-"
    if len(id_str) <= length:
        return id_str
    return f"{id_str[:length]}..."

# %% ../nbs/utils.ipynb #review-utils-format-char-range
def format_char_range(
    start_char:Optional[int],  # Start character index
    end_char:Optional[int],  # End character index
) -> str:  # Formatted range string (e.g., "char:25-68")
    """Format character range for source reference display."""
    if start_char is None or end_char is None:
        return "char:-"
    return f"char:{start_char}-{end_char}"

# %% ../nbs/utils.ipynb #review-utils-format-source-info
def format_source_info(
    provider_id:Optional[str],  # Source provider identifier
    source_id:Optional[str],  # Source record ID
    start_char:Optional[int]=None,  # Start character index
    end_char:Optional[int]=None,  # End character index
) -> str:  # Formatted source info string
    """Format source info for display in review cards."""
    provider = provider_id if provider_id else "-"
    record = truncate_id(source_id)
    char_range = format_char_range(start_char, end_char)
    return f"{provider} | {record} | {char_range}"
