"""Audio playback controls: speed selector and auto-navigate toggle"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/audio_controls.ipynb.

# %% auto #0
__all__ = ['PLAYBACK_SPEEDS', 'AudioControlIds', 'render_speed_selector', 'render_auto_navigate_toggle', 'render_audio_controls']

# %% ../../nbs/components/audio_controls.ipynb #audio-ctrl-imports
from typing import Any, List

from fasthtml.common import Div, Span, Select, Option, Input, Label

# DaisyUI components
from cjm_fasthtml_daisyui.components.data_input.select import select, select_sizes
from cjm_fasthtml_daisyui.components.data_input.toggle import toggle, toggle_sizes
from cjm_fasthtml_daisyui.utilities.semantic_colors import text_dui

# Tailwind utilities
from cjm_fasthtml_tailwind.utilities.spacing import m
from cjm_fasthtml_tailwind.utilities.typography import font_size
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import flex_display, items, gap
from cjm_fasthtml_tailwind.core.base import combine_classes

# %% ../../nbs/components/audio_controls.ipynb #audio-ctrl-ids
class AudioControlIds:
    """HTML ID constants for audio control elements."""
    
    SPEED_SELECT = "sd-review-speed-select"
    AUTO_NAV_TOGGLE = "sd-review-auto-nav-toggle"
    AUDIO_CONTROLS = "sd-review-audio-controls"

# %% ../../nbs/components/audio_controls.ipynb #audio-ctrl-speeds
# Available playback speeds (value, label)
PLAYBACK_SPEEDS: List[tuple] = [
    (0.5, "0.5x"),
    (0.75, "0.75x"),
    (1.0, "1x"),
    (1.25, "1.25x"),
    (1.5, "1.5x"),
    (2.0, "2x"),
    (2.5, "2.5x"),
    (3.0, "3x"),
]

# %% ../../nbs/components/audio_controls.ipynb #audio-ctrl-speed-comp
def render_speed_selector(
    current_speed:float=1.0,  # Current playback speed
    change_url:str="",  # URL to POST speed changes to
) -> Any:  # Speed selector component
    """Render playback speed selector dropdown."""
    options = [
        Option(
            label,
            value=str(speed),
            selected=(speed == current_speed),
        )
        for speed, label in PLAYBACK_SPEEDS
    ]
    
    # Build HTMX attributes if URL provided
    htmx_attrs = {}
    if change_url:
        htmx_attrs = {
            "hx_post": change_url,
            "hx_trigger": "change",
            "hx_swap": "none",
        }
    
    # Client-side JS to update playback speed immediately
    onchange_js = "window._reviewPlaybackSpeed = parseFloat(this.value); if(window.DEBUG_REVIEW_AUDIO) console.log('[REVIEW_AUDIO] Speed changed to:', this.value);"
    
    return Div(
        Span(
            "Speed:",
            cls=combine_classes(font_size.sm, text_dui.base_content.opacity(70), m.r(2))
        ),
        Select(
            *options,
            id=AudioControlIds.SPEED_SELECT,
            name="speed",
            cls=combine_classes(select, select_sizes.sm),
            onchange=onchange_js,
            **htmx_attrs,
        ),
        cls=combine_classes(flex_display, items.center)
    )

# %% ../../nbs/components/audio_controls.ipynb #audio-ctrl-autonav-comp
def render_auto_navigate_toggle(
    enabled:bool=False,  # Whether auto-navigate is enabled
    toggle_url:str="",  # URL to POST toggle changes to
) -> Any:  # Auto-navigate toggle component
    """Render auto-navigate toggle switch."""
    # Build HTMX attributes if URL provided
    htmx_attrs = {}
    if toggle_url:
        htmx_attrs = {
            "hx_post": toggle_url,
            "hx_trigger": "change",
            "hx_swap": "none",
        }
    
    # Client-side JS to update auto-navigate flag immediately
    onchange_js = "window._reviewAutoNavigate = this.checked; if(window.DEBUG_REVIEW_AUDIO) console.log('[REVIEW_AUDIO] Auto-navigate changed to:', this.checked);"
    
    return Div(
        Label(
            Span(
                "Auto:",
                cls=combine_classes(font_size.sm, text_dui.base_content.opacity(70), m.r(2))
            ),
            Input(
                type="checkbox",
                id=AudioControlIds.AUTO_NAV_TOGGLE,
                name="auto_navigate",
                checked=enabled,
                cls=combine_classes(toggle, toggle_sizes.sm),
                onchange=onchange_js,
                **htmx_attrs,
            ),
            cls=combine_classes(flex_display, items.center)
        ),
        cls=combine_classes(flex_display, items.center)
    )

# %% ../../nbs/components/audio_controls.ipynb #audio-ctrl-combined-comp
def render_audio_controls(
    current_speed:float=1.0,  # Current playback speed
    auto_navigate:bool=False,  # Whether auto-navigate is enabled
    speed_url:str="",  # URL for speed changes
    auto_nav_url:str="",  # URL for auto-navigate toggle
    oob:bool=False,  # Whether to render as OOB swap
) -> Any:  # Combined audio controls component
    """Render combined audio controls (speed selector + auto-navigate toggle)."""
    return Div(
        render_speed_selector(current_speed, speed_url),
        render_auto_navigate_toggle(auto_navigate, auto_nav_url),
        id=AudioControlIds.AUDIO_CONTROLS,
        cls=combine_classes(flex_display, items.center, gap(4)),
        hx_swap_oob="true" if oob else None,
    )
