"""JavaScript callbacks for the review card stack"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/callbacks.ipynb.

# %% auto #0
__all__ = ['generate_review_callbacks_script']

# %% ../../nbs/components/callbacks.ipynb #review-cb-imports
from cjm_fasthtml_card_stack.core.config import CardStackConfig
from cjm_fasthtml_card_stack.core.html_ids import CardStackHtmlIds
from cjm_fasthtml_card_stack.core.button_ids import CardStackButtonIds
from cjm_fasthtml_card_stack.core.models import CardStackUrls
from cjm_fasthtml_card_stack.js.core import generate_card_stack_js

# %% ../../nbs/components/callbacks.ipynb #review-cb-gen
def generate_review_callbacks_script(
    ids:CardStackHtmlIds,  # Card stack HTML IDs
    button_ids:CardStackButtonIds,  # Card stack button IDs
    config:CardStackConfig,  # Card stack configuration
    urls:CardStackUrls,  # Card stack URL bundle
    container_id:str,  # ID of the review container (parent of card stack)
) -> any:  # Script element with all JavaScript callbacks
    """Generate JavaScript for review card stack."""
    return generate_card_stack_js(
        ids=ids,
        button_ids=button_ids,
        config=config,
        urls=urls,
        container_id=container_id,
    )
