"""Focus change callback and audio playback JavaScript for the review card stack"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/callbacks.ipynb.

# %% auto #0
__all__ = ['REVIEW_AUDIO_CONFIG', 'generate_review_callbacks_script']

# %% ../../nbs/components/callbacks.ipynb #review-cb-imports
from cjm_fasthtml_card_stack.core.config import CardStackConfig
from cjm_fasthtml_card_stack.core.html_ids import CardStackHtmlIds
from cjm_fasthtml_card_stack.core.button_ids import CardStackButtonIds
from cjm_fasthtml_card_stack.core.models import CardStackUrls
from cjm_fasthtml_card_stack.js.core import generate_card_stack_js

from cjm_fasthtml_web_audio.models import WebAudioConfig
from cjm_fasthtml_web_audio.js import generate_web_audio_js

# %% ../../nbs/components/callbacks.ipynb #cvj04t6vh8
REVIEW_AUDIO_CONFIG = WebAudioConfig(
    namespace="review",
    indicator_selector=".review-playing-indicator",
    enable_speed=True,
    enable_replay=True,
    enable_auto_nav=True,
)

# %% ../../nbs/components/callbacks.ipynb #review-cb-gen
def generate_review_callbacks_script(
    ids:CardStackHtmlIds,  # Card stack HTML IDs
    button_ids:CardStackButtonIds,  # Card stack button IDs
    config:CardStackConfig,  # Card stack configuration
    urls:CardStackUrls,  # Card stack URL bundle
    container_id:str,  # ID of the review container (parent of card stack)
    focus_input_id:str,  # ID of hidden input for focused segment index
) -> any:  # Script element with all JavaScript callbacks
    """Generate JavaScript for review card stack with Web Audio API audition."""
    web_audio_js = generate_web_audio_js(
        config=REVIEW_AUDIO_CONFIG,
        focus_input_id=focus_input_id,
        card_stack_id=ids.card_stack,
        nav_down_btn_id=button_ids.nav_down,
    )

    return generate_card_stack_js(
        ids=ids,
        button_ids=button_ids,
        config=config,
        urls=urls,
        container_id=container_id,
        extra_scripts=(web_audio_js,),
    )
