"""Card stack configuration, HTML IDs, and button IDs for the review card stack"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/card_stack_config.ipynb.

# %% auto #0
__all__ = ['REVIEW_CS_CONFIG', 'REVIEW_CS_IDS', 'REVIEW_CS_BTN_IDS']

# %% ../../nbs/components/card_stack_config.ipynb #review-csc-exports
from cjm_fasthtml_card_stack.core.config import CardStackConfig, CardStackStyleConfig
from cjm_fasthtml_card_stack.core.html_ids import CardStackHtmlIds
from cjm_fasthtml_card_stack.core.button_ids import CardStackButtonIds

# %% ../../nbs/components/card_stack_config.ipynb #review-csc-config
REVIEW_CS_CONFIG = CardStackConfig(
    prefix="sd-review",
    card_width_min=30,
    card_width_max=70,
    card_width_step=5,
    style=CardStackStyleConfig(
        section_gap="0.75rem",
        slot_padding="0.125rem",
        viewport_padding_x='0.0rem',
        viewport_padding_y='0.0rem'
    ),
)

REVIEW_CS_IDS = CardStackHtmlIds(prefix=REVIEW_CS_CONFIG.prefix)
REVIEW_CS_BTN_IDS = CardStackButtonIds(prefix=REVIEW_CS_CONFIG.prefix)
