"""Review-specific keyboard building blocks for assembly into a KeyboardManager"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/keyboard_config.ipynb.

# %% auto #0
__all__ = ['create_review_kb_parts']

# %% ../../nbs/components/keyboard_config.ipynb #review-kb-imports
from typing import Tuple

# Keyboard navigation library
from cjm_fasthtml_keyboard_navigation.core.focus_zone import FocusZone
from cjm_fasthtml_keyboard_navigation.core.actions import KeyAction

# Card stack library
from cjm_fasthtml_card_stack.core.config import CardStackConfig
from cjm_fasthtml_card_stack.core.html_ids import CardStackHtmlIds
from cjm_fasthtml_card_stack.core.button_ids import CardStackButtonIds
from cjm_fasthtml_card_stack.keyboard.actions import (
    create_card_stack_focus_zone, create_card_stack_nav_actions,
)

# %% ../../nbs/components/keyboard_config.ipynb #review-kb-parts
def create_review_kb_parts(
    ids:CardStackHtmlIds,  # Card stack HTML IDs
    button_ids:CardStackButtonIds,  # Card stack button IDs for navigation
    config:CardStackConfig,  # Card stack configuration
) -> Tuple[FocusZone, tuple, tuple]:  # (zone, actions, modes)
    """Create review-specific keyboard building blocks."""
    # Card stack zone from library
    # onReviewFocusChange callback handles audio playback on navigation
    card_zone = create_card_stack_focus_zone(
        ids=ids,
        on_focus_change="onReviewFocusChange",
    )

    # Card stack navigation actions from library (arrows, page jump, first/last, width)
    nav_actions = create_card_stack_nav_actions(
        zone_id=card_zone.id,
        button_ids=button_ids,
        config=config,
    )
    
    # Replay action — Space key to replay current segment's audio
    replay_action = KeyAction(
        key=" ",  # Space
        js_callback="replayReviewSegment",
        zone_ids=(card_zone.id,),
        description="Replay segment",
        hint_group="Audio",
    )

    # Combine all actions
    actions = nav_actions + (replay_action,)
    modes = ()  # No sub-modes

    return card_zone, actions, modes
