"""Composable render functions for the review card stack step"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/step_renderer.ipynb.

# %% auto #0
__all__ = ['DEBUG_REVIEW_RENDER', 'render_review_toolbar', 'render_review_stats', 'render_review_content', 'render_review_footer',
           'render_review_step']

# %% ../../nbs/components/step_renderer.ipynb #review-sr-imports
from typing import Any, List, Optional

from fasthtml.common import Div, Span, Audio

# DaisyUI components
from cjm_fasthtml_daisyui.utilities.semantic_colors import text_dui

# Tailwind utilities
from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.sizing import w, h, min_h
from cjm_fasthtml_tailwind.utilities.typography import font_size
from cjm_fasthtml_tailwind.utilities.layout import overflow, display_tw
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import (
    flex_display, flex_direction, justify, items, gap, grow
)
from cjm_fasthtml_tailwind.core.base import combine_classes

# Card stack library
from cjm_fasthtml_card_stack.components.viewport import render_viewport
from cjm_fasthtml_card_stack.components.controls import render_card_count_select
from cjm_fasthtml_card_stack.components.progress import render_progress_indicator
from cjm_fasthtml_card_stack.core.models import CardStackState
from cjm_fasthtml_card_stack.core.constants import DEFAULT_VISIBLE_COUNT, DEFAULT_CARD_WIDTH
from cjm_fasthtml_card_stack.keyboard.actions import render_card_stack_action_buttons

# Review configuration
from cjm_transcript_review.components.card_stack_config import (
    REVIEW_CS_CONFIG, REVIEW_CS_IDS, REVIEW_CS_BTN_IDS,
)

# Local imports
from ..html_ids import ReviewHtmlIds
from ..models import ReviewUrls
from cjm_transcript_review.components.review_card import (
    create_review_card_renderer, AssembledSegment
)
from .callbacks import generate_review_callbacks_script

# Debug flag
DEBUG_REVIEW_RENDER = False

# %% ../../nbs/components/step_renderer.ipynb #review-sr-toolbar
def render_review_toolbar(
    visible_count:int=DEFAULT_VISIBLE_COUNT,  # Current visible card count
    is_auto_mode:bool=False,  # Whether card count is in auto-adjust mode
    oob:bool=False,  # Whether to render as OOB swap
) -> Any:  # Toolbar component
    """Render the review toolbar with card count selector."""
    return Div(
        # Spacer
        Div(cls=str(grow())),

        # Right: Card count selector
        Div(
            Span(
                "Cards:",
                cls=combine_classes(font_size.sm, text_dui.base_content.opacity(70), m.r(2))
            ),
            render_card_count_select(
                REVIEW_CS_CONFIG, REVIEW_CS_IDS,
                current_count=visible_count,
                is_auto_mode=is_auto_mode,
            ),
            cls=combine_classes(flex_display, items.center)
        ),

        id=ReviewHtmlIds.REVIEW_TOOLBAR,
        cls=combine_classes(flex_display, gap(2), items.center),
        hx_swap_oob="true" if oob else None
    )

# %% ../../nbs/components/step_renderer.ipynb #review-sr-stats
def render_review_stats(
    assembled:List[AssembledSegment],  # Assembled segments
    oob:bool=False,  # Whether to render as OOB swap
) -> Any:  # Statistics component
    """Render review statistics."""
    total = len(assembled)
    total_dur = sum(a.vad_chunk.duration for a in assembled) if assembled else 0.0

    return Div(
        Span(
            f"{total} segments \u00b7 {total_dur:.1f}s total",
            cls=combine_classes(font_size.sm, text_dui.base_content.opacity(70))
        ),
        id=ReviewHtmlIds.REVIEW_STATS,
        hx_swap_oob="true" if oob else None
    )

# %% ../../nbs/components/step_renderer.ipynb #review-sr-body
def render_review_content(
    assembled:List[AssembledSegment],  # Assembled segments to display
    focused_index:int,  # Currently focused segment index
    visible_count:int,  # Number of visible cards in viewport
    card_width:int,  # Card stack width in rem
    urls:ReviewUrls,  # URL bundle for review routes
    media_path:Optional[str]=None,  # Path to audio file for playback
    kb_system:Optional[Any]=None,  # Rendered keyboard system (None when KB managed externally)
) -> Any:  # Main content area
    """Render the review content area with card stack viewport."""
    if DEBUG_REVIEW_RENDER:
        print(f"[REVIEW_RENDER] render_review_content called")
        print(f"[REVIEW_RENDER] assembled count: {len(assembled)}")
        print(f"[REVIEW_RENDER] media_path: {media_path}")

    # Create card renderer callback
    card_renderer = create_review_card_renderer()

    # Build CardStackState for library viewport
    cs_state = CardStackState(
        focused_index=focused_index,
        visible_count=visible_count,
        card_width=card_width,
    )

    # Render viewport from library
    viewport = render_viewport(
        card_items=assembled,
        state=cs_state,
        config=REVIEW_CS_CONFIG,
        ids=REVIEW_CS_IDS,
        urls=urls.card_stack,
        render_card=card_renderer,
        form_input_name="segment_index",
    )

    # Build audio source URL
    audio_src = ""
    if urls.audio_src and media_path:
        audio_src = f"{urls.audio_src}?path={media_path}"

    # Generate card stack JavaScript callbacks with audio playback
    callbacks_script = generate_review_callbacks_script(
        ids=REVIEW_CS_IDS,
        button_ids=REVIEW_CS_BTN_IDS,
        config=REVIEW_CS_CONFIG,
        urls=urls.card_stack,
        container_id=ReviewHtmlIds.REVIEW_CONTENT,
        focus_input_id=REVIEW_CS_IDS.focused_index_input,
        audio_player_id=ReviewHtmlIds.AUDIO_PLAYER,
    )

    # Keyboard system elements (optional — may be managed at demo app level)
    kb_elements = ()
    if kb_system is not None:
        kb_elements = (kb_system.script, kb_system.hidden_inputs, kb_system.action_buttons)

    return Div(
        # Card stack viewport
        viewport,

        # Keyboard navigation system (when provided)
        *kb_elements,

        # Hidden audio element for audition playback
        Audio(
            id=ReviewHtmlIds.AUDIO_PLAYER,
            src=audio_src,
            preload="metadata",
            cls=str(display_tw.hidden),
        ),

        # Hidden action buttons for JS-triggered card stack nav
        render_card_stack_action_buttons(REVIEW_CS_BTN_IDS, urls.card_stack, REVIEW_CS_IDS),

        # JavaScript callbacks (card stack JS + audio playback)
        callbacks_script,

        id=ReviewHtmlIds.REVIEW_CONTENT,
        cls=combine_classes(grow(), min_h(0), overflow.hidden, flex_display, flex_direction.col)
    )

# %% ../../nbs/components/step_renderer.ipynb #review-sr-footer
def render_review_footer(
    assembled:List[AssembledSegment],  # Assembled segments
    focused_index:int,  # Currently focused segment index
) -> Any:  # Footer content with progress indicator and stats
    """Render footer content with progress indicator and statistics."""
    total_segments = len(assembled)

    return Div(
        render_progress_indicator(focused_index, total_segments, REVIEW_CS_IDS, label="Segment"),
        render_review_stats(assembled),
        id=ReviewHtmlIds.REVIEW_FOOTER,
        cls=combine_classes(flex_display, justify.between, items.center, gap(4))
    )

# %% ../../nbs/components/step_renderer.ipynb #review-sr-step
def render_review_step(
    assembled:List[AssembledSegment],  # Assembled segments to display
    focused_index:int=0,  # Currently focused segment index
    visible_count:int=DEFAULT_VISIBLE_COUNT,  # Number of visible cards
    is_auto_mode:bool=False,  # Whether card count is in auto-adjust mode
    card_width:int=DEFAULT_CARD_WIDTH,  # Card stack width in rem
    urls:ReviewUrls=None,  # URL bundle for review routes
    media_path:Optional[str]=None,  # Path to audio file for playback
) -> Any:  # Complete review step component
    """Render the complete review step with toolbar, content, and footer."""
    urls = urls or ReviewUrls()
    
    return Div(
        # Toolbar
        render_review_toolbar(visible_count, is_auto_mode),
        
        # Main content area
        render_review_content(
            assembled, focused_index, visible_count, card_width, urls, media_path
        ),
        
        # Footer
        render_review_footer(assembled, focused_index),
        
        id=ReviewHtmlIds.REVIEW_CONTAINER,
        cls=combine_classes(
            flex_display, flex_direction.col, gap(4),
            h.full, p(4)
        )
    )
