"""Composable render functions for the review card stack step"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/components/step_renderer.ipynb.

# %% auto #0
__all__ = ['DEBUG_REVIEW_RENDER', 'render_review_toolbar', 'render_review_stats', 'render_review_source_position',
           'render_review_keyboard_hints', 'render_review_content', 'render_review_footer', 'render_review_step']

# %% ../../nbs/components/step_renderer.ipynb #review-sr-imports
from typing import Any, List, Optional

from fasthtml.common import Div, Span, Details, Summary

# DaisyUI components
from cjm_fasthtml_daisyui.utilities.semantic_colors import text_dui, bg_dui
from cjm_fasthtml_daisyui.components.data_display.collapse import (
    collapse, collapse_title, collapse_content, collapse_modifiers
)

# Tailwind utilities
from cjm_fasthtml_tailwind.utilities.spacing import p, m
from cjm_fasthtml_tailwind.utilities.sizing import w, h, min_h
from cjm_fasthtml_tailwind.utilities.typography import font_size, font_weight
from cjm_fasthtml_tailwind.utilities.layout import overflow
from cjm_fasthtml_tailwind.utilities.flexbox_and_grid import (
    flex_display, flex_direction, justify, items, gap, grow
)
from cjm_fasthtml_tailwind.core.base import combine_classes

# Keyboard navigation
from cjm_fasthtml_keyboard_navigation.components.system import render_keyboard_system
from cjm_fasthtml_keyboard_navigation.components.hints import render_keyboard_hints

# Card stack library
from cjm_fasthtml_card_stack.components.viewport import render_viewport
from cjm_fasthtml_card_stack.components.controls import render_card_count_select
from cjm_fasthtml_card_stack.components.progress import render_progress_indicator
from cjm_fasthtml_card_stack.core.models import CardStackState
from cjm_fasthtml_card_stack.core.constants import DEFAULT_VISIBLE_COUNT, DEFAULT_CARD_WIDTH
from cjm_fasthtml_card_stack.keyboard.actions import (
    render_card_stack_action_buttons, build_card_stack_url_map
)

# Web Audio library
from cjm_fasthtml_web_audio.components import render_audio_urls_input

# VAD alignment utilities (for boundary detection across assembled segments)
from cjm_transcript_vad_align.utils import (
    get_audio_file_boundaries, get_audio_file_count, get_audio_file_position,
)

# Review configuration
from cjm_transcript_review.components.card_stack_config import (
    REVIEW_CS_CONFIG, REVIEW_CS_IDS, REVIEW_CS_BTN_IDS,
)
from .keyboard_config import create_review_keyboard_manager

# Local imports
from ..html_ids import ReviewHtmlIds
from ..models import ReviewUrls
from cjm_transcript_review.components.review_card import (
    create_review_card_renderer, AssembledSegment
)
from cjm_transcript_review.components.callbacks import (
    generate_review_callbacks_script, REVIEW_AUDIO_CONFIG,
)
from .audio_controls import render_audio_controls

# Debug flag
DEBUG_REVIEW_RENDER = False

# %% ../../nbs/components/step_renderer.ipynb #review-sr-toolbar
def render_review_toolbar(
    visible_count:int=DEFAULT_VISIBLE_COUNT,  # Current visible card count
    is_auto_mode:bool=False,  # Whether card count is in auto-adjust mode
    playback_speed:float=1.0,  # Current playback speed
    auto_navigate:bool=False,  # Whether auto-navigate is enabled
    urls:ReviewUrls=None,  # URL bundle for audio control routes
    oob:bool=False,  # Whether to render as OOB swap
) -> Any:  # Toolbar component
    """Render the review toolbar with audio controls and card count selector."""
    urls = urls or ReviewUrls()
    
    return Div(
        # Left: Audio controls (speed + auto-navigate)
        render_audio_controls(
            current_speed=playback_speed,
            auto_navigate=auto_navigate,
            speed_url=urls.speed_change,
            auto_nav_url=urls.toggle_auto_nav,
        ),
        
        # Spacer
        Div(cls=str(grow())),

        # Right: Card count selector
        Div(
            Span(
                "Cards:",
                cls=combine_classes(font_size.sm, text_dui.base_content.opacity(70), m.r(2))
            ),
            render_card_count_select(
                REVIEW_CS_CONFIG, REVIEW_CS_IDS,
                current_count=visible_count,
                is_auto_mode=is_auto_mode,
            ),
            cls=combine_classes(flex_display, items.center)
        ),

        id=ReviewHtmlIds.REVIEW_TOOLBAR,
        cls=combine_classes(flex_display, gap(2), items.center),
        hx_swap_oob="true" if oob else None
    )

# %% ../../nbs/components/step_renderer.ipynb #review-sr-stats
def render_review_stats(
    assembled:List[AssembledSegment],  # Assembled segments
    oob:bool=False,  # Whether to render as OOB swap
) -> Any:  # Statistics component
    """Render review statistics."""
    total = len(assembled)
    total_dur = sum(a.vad_chunk.duration for a in assembled) if assembled else 0.0
    chunks = [a.vad_chunk for a in assembled]
    file_count = get_audio_file_count(chunks)

    stats_text = f"{total} segments \u00b7 {total_dur:.1f}s total"
    if file_count > 1:
        stats_text += f" \u00b7 {file_count} files"

    return Div(
        Span(
            stats_text,
            cls=combine_classes(font_size.sm, text_dui.base_content.opacity(70))
        ),
        id=ReviewHtmlIds.REVIEW_STATS,
        hx_swap_oob="true" if oob else None
    )

#| export
def render_review_source_position(
    assembled:List[AssembledSegment],  # Assembled segments
    focused_index:int=0,  # Currently focused segment index
    oob:bool=False,  # Whether to render as OOB swap
) -> Any:  # Audio file position indicator (empty if single file)
    """Render audio file position indicator for the focused segment."""
    chunks = [a.vad_chunk for a in assembled]
    file_count = get_audio_file_count(chunks)

    content = ""
    if file_count > 1:
        pos = get_audio_file_position(chunks, focused_index)
        if pos is not None:
            content = f"File {pos} of {file_count}"

    return Span(
        content,
        id=ReviewHtmlIds.SOURCE_POSITION,
        cls=combine_classes(font_size.sm, text_dui.base_content.opacity(70)),
        hx_swap_oob="true" if oob else None,
    )

# %% ../../nbs/components/step_renderer.ipynb #bg7siauxclw
def render_review_keyboard_hints(
    oob:bool=False,  # Whether to render as OOB swap
) -> Any:  # Collapsible keyboard hints component
    """Render keyboard shortcut hints in a collapsible container."""
    # Create keyboard manager to extract hints
    kb_manager = create_review_keyboard_manager(
        ids=REVIEW_CS_IDS,
        button_ids=REVIEW_CS_BTN_IDS,
        config=REVIEW_CS_CONFIG,
    )
    
    hints = render_keyboard_hints(
        kb_manager,
        include_navigation=True,
        include_zone_switch=False,  # Single zone, no switching
        badge_style="outline",
        container_id="review-kb-hints",
        use_icons=False
    )
    
    return Details(
        Summary(
            "Keyboard Shortcuts",
            cls=combine_classes(collapse_title, font_size.sm, font_weight.medium)
        ),
        Div(
            hints,
            cls=collapse_content
        ),
        id=ReviewHtmlIds.KEYBOARD_HINTS,
        cls=combine_classes(collapse, collapse_modifiers.arrow, bg_dui.base_200),
        hx_swap_oob="true" if oob else None
    )

# %% ../../nbs/components/step_renderer.ipynb #review-sr-body
def render_review_content(
    assembled:List[AssembledSegment],  # Assembled segments to display
    focused_index:int,  # Currently focused segment index
    visible_count:int,  # Number of visible cards in viewport
    card_width:int,  # Card stack width in rem
    urls:ReviewUrls,  # URL bundle for review routes
    audio_urls:Optional[List[str]]=None,  # Audio file URLs for Web Audio API
) -> Any:  # Main content area
    """Render the review content area with card stack viewport and keyboard system."""
    if DEBUG_REVIEW_RENDER:
        print(f"[REVIEW_RENDER] render_review_content called")
        print(f"[REVIEW_RENDER] assembled count: {len(assembled)}")
        print(f"[REVIEW_RENDER] audio_urls count: {len(audio_urls) if audio_urls else 0}")

    # Compute audio file boundaries for visual indicators
    chunks = [a.vad_chunk for a in assembled]
    boundaries = get_audio_file_boundaries(chunks)

    # Create card renderer callback with boundary info
    card_renderer = create_review_card_renderer(audio_file_boundaries=boundaries)

    # Build CardStackState for library viewport
    cs_state = CardStackState(
        focused_index=focused_index,
        visible_count=visible_count,
        card_width=card_width,
    )

    # Render viewport from library
    viewport = render_viewport(
        card_items=assembled,
        state=cs_state,
        config=REVIEW_CS_CONFIG,
        ids=REVIEW_CS_IDS,
        urls=urls.card_stack,
        render_card=card_renderer,
        form_input_name="segment_index",
    )

    # Generate card stack JavaScript callbacks with Web Audio API playback
    callbacks_script = generate_review_callbacks_script(
        ids=REVIEW_CS_IDS,
        button_ids=REVIEW_CS_BTN_IDS,
        config=REVIEW_CS_CONFIG,
        urls=urls.card_stack,
        container_id=ReviewHtmlIds.REVIEW_CONTENT,
        focus_input_id=REVIEW_CS_IDS.focused_index_input,
    )

    # Build keyboard system internally
    kb_manager = create_review_keyboard_manager(
        ids=REVIEW_CS_IDS,
        button_ids=REVIEW_CS_BTN_IDS,
        config=REVIEW_CS_CONFIG,
    )
    
    # URL mappings (card stack navigation)
    include_selector = f"#{REVIEW_CS_IDS.focused_index_input}"
    url_map = build_card_stack_url_map(REVIEW_CS_BTN_IDS, urls.card_stack)
    
    # Target, include, and swap maps
    target = f"#{REVIEW_CS_IDS.card_stack}"
    target_map = {btn_id: target for btn_id in url_map}
    include_map = {btn_id: include_selector for btn_id in url_map}
    swap_map = {btn_id: "none" for btn_id in url_map}  # OOB swaps handle updates
    
    kb_system = render_keyboard_system(
        kb_manager,
        url_map=url_map,
        target_map=target_map,
        include_map=include_map,
        swap_map=swap_map,
        show_hints=False,  # Hints rendered separately
        include_state_inputs=True,
    )

    return Div(
        # Card stack viewport
        viewport,

        # Keyboard navigation system
        kb_system.script,
        kb_system.hidden_inputs,
        kb_system.action_buttons,

        # Audio URLs hidden input for Web Audio API parallel decode
        render_audio_urls_input(REVIEW_AUDIO_CONFIG, audio_urls or []),

        # Hidden action buttons for JS-triggered card stack nav
        render_card_stack_action_buttons(REVIEW_CS_BTN_IDS, urls.card_stack, REVIEW_CS_IDS),

        # JavaScript callbacks (card stack JS + Web Audio API playback)
        callbacks_script,

        id=ReviewHtmlIds.REVIEW_CONTENT,
        cls=combine_classes(grow(), min_h(0), overflow.hidden, flex_display, flex_direction.col)
    )

# %% ../../nbs/components/step_renderer.ipynb #review-sr-footer
def render_review_footer(
    assembled:List[AssembledSegment],  # Assembled segments
    focused_index:int,  # Currently focused segment index
) -> Any:  # Footer content with progress indicator, source position, and stats
    """Render footer content with progress indicator, source position, and statistics."""
    total_segments = len(assembled)

    return Div(
        Div(
            render_progress_indicator(focused_index, total_segments, REVIEW_CS_IDS, label="Segment"),
            render_review_source_position(assembled, focused_index),
            cls=combine_classes(flex_display, items.center, gap(3)),
        ),
        render_review_stats(assembled),
        id=ReviewHtmlIds.REVIEW_FOOTER,
        cls=combine_classes(flex_display, justify.between, items.center, gap(4))
    )

# %% ../../nbs/components/step_renderer.ipynb #review-sr-step
def render_review_step(
    assembled:List[AssembledSegment],  # Assembled segments to display
    focused_index:int=0,  # Currently focused segment index
    visible_count:int=DEFAULT_VISIBLE_COUNT,  # Number of visible cards
    is_auto_mode:bool=False,  # Whether card count is in auto-adjust mode
    card_width:int=DEFAULT_CARD_WIDTH,  # Card stack width in rem
    playback_speed:float=1.0,  # Current playback speed
    auto_navigate:bool=False,  # Whether auto-navigate is enabled
    urls:ReviewUrls=None,  # URL bundle for review routes
    audio_urls:Optional[List[str]]=None,  # Audio file URLs for Web Audio API
) -> Any:  # Complete review step component
    """Render the complete review step with toolbar, content, and footer."""
    urls = urls or ReviewUrls()
    
    return Div(
        # Keyboard hints (collapsible)
        render_review_keyboard_hints(),
        
        # Toolbar with audio controls
        render_review_toolbar(
            visible_count, is_auto_mode,
            playback_speed=playback_speed,
            auto_navigate=auto_navigate,
            urls=urls,
        ),
        
        # Main content area (includes keyboard system internally)
        render_review_content(
            assembled, focused_index, visible_count, card_width, urls, audio_urls,
        ),
        
        # Footer
        render_review_footer(assembled, focused_index),
        
        id=ReviewHtmlIds.REVIEW_CONTAINER,
        cls=combine_classes(
            flex_display, flex_direction.col, gap(4),
            h.full, p(4)
        )
    )
